import type { Exercise } from "./types";
import { repRangeFor } from "./repRangeTemplates";

/**
 * 種目の初期シードデータ。段階1は先頭5種目、段階4で全種目を対象にする。
 * materialStatusは全て"unconfirmed"。出典・利用条件が確認できた時点で
 * 個別にconfirmedへ変更し、materialUrl/materialSourceを設定する(捏造しない)。
 */
export const INITIAL_EXERCISES: Exercise[] = [
  // --- 段階1: 最初の5種目 ---
  {
    id: "dumbbell-bench-press",
    name: "ダンベルベンチプレス",
    primaryMuscle: "大胸筋",
    secondaryMuscles: ["上腕三頭筋", "三角筋前部"],
    requiredEquipment: ["dumbbell", "bench"],
    requiresBenchAngle: false,
    loadType: "dumbbellPerHand",
    unilateral: false,
    defaultPieceCount: 2,
    formTips: [
      "ベンチに仰向けになり肩甲骨を寄せる",
      "ダンベルは胸の横まで下ろす",
      "手首を立てたまま押し上げる",
    ],
    commonMistakes: ["肩がすくむ", "反動を使う", "可動域が浅い"],
    alternativeExerciseIds: ["dumbbell-floor-press"],
    materialStatus: "unconfirmed",
    repRangeByGoal: repRangeFor("compound"),
    description: "ベンチに仰向けでダンベルを両手に持ち押し上げる基本種目。",
  },
  {
    id: "dumbbell-shoulder-press",
    name: "ダンベルショルダープレス",
    primaryMuscle: "三角筋",
    secondaryMuscles: ["上腕三頭筋"],
    requiredEquipment: ["dumbbell"],
    requiresBenchAngle: false,
    loadType: "dumbbellPerHand",
    unilateral: false,
    defaultPieceCount: 2,
    formTips: ["肘を肩の高さから開始する", "頭上でダンベルが正面から見て一直線", "反り腰にならない"],
    commonMistakes: ["反動を使う", "肘を伸ばしきって固定する"],
    alternativeExerciseIds: [],
    materialStatus: "unconfirmed",
    repRangeByGoal: repRangeFor("compound"),
    description: "座位または立位で両手のダンベルを頭上に押し上げる。",
  },
  {
    id: "dumbbell-one-arm-row",
    name: "ダンベルワンハンドロウ",
    primaryMuscle: "広背筋",
    secondaryMuscles: ["僧帽筋", "上腕二頭筋"],
    requiredEquipment: ["dumbbell", "bench"],
    requiresBenchAngle: false,
    loadType: "dumbbellPerHand",
    unilateral: true,
    defaultPieceCount: 1,
    formTips: ["ベンチに片膝・片手をつき体を安定させる", "肘を後ろに引く", "背中が丸まらないようにする"],
    commonMistakes: ["体をひねって反動を使う", "可動域が浅い"],
    alternativeExerciseIds: [],
    materialStatus: "unconfirmed",
    repRangeByGoal: repRangeFor("compound"),
    description: "ベンチに片手・片膝をつき、片手ずつダンベルを引き上げる。左右別に記録する。",
  },
  {
    id: "goblet-squat",
    name: "ゴブレットスクワット",
    primaryMuscle: "大腿四頭筋",
    secondaryMuscles: ["臀筋", "体幹"],
    requiredEquipment: ["dumbbell"],
    requiresBenchAngle: false,
    loadType: "dumbbellPerHand",
    unilateral: false,
    defaultPieceCount: 1,
    formTips: ["ダンベルを胸の前で両手で保持する", "膝がつま先より内側に入らない", "股関節から折りたたむ"],
    commonMistakes: ["かかとが浮く", "背中が丸まる"],
    alternativeExerciseIds: ["bodyweight-squat"],
    materialStatus: "unconfirmed",
    repRangeByGoal: repRangeFor("compound"),
    description: "ダンベル1個を両手で胸の前に持ち、しゃがみ込む。",
  },
  {
    id: "pushup-with-bar",
    name: "腕立て伏せ（プッシュバー使用）",
    primaryMuscle: "大胸筋",
    secondaryMuscles: ["上腕三頭筋", "三角筋前部"],
    requiredEquipment: ["pushUpBar"],
    requiresBenchAngle: false,
    loadType: "bodyweight",
    unilateral: false,
    defaultPieceCount: 1,
    formTips: ["プッシュバーを肩幅よりやや広く置く", "体を一直線に保つ", "胸がバーの高さまで下がる"],
    commonMistakes: ["腰が反る・落ちる", "可動域が浅い"],
    alternativeExerciseIds: ["dumbbell-floor-press"],
    materialStatus: "unconfirmed",
    repRangeByGoal: repRangeFor("bodyweight"),
    description: "プッシュバーを握って行う腕立て伏せ。自重種目としてダンベル種目と別に集計する。",
  },

  // --- 段階4: 追加種目（15〜20種目への拡張） ---
  {
    id: "dumbbell-curl",
    name: "ダンベルカール",
    primaryMuscle: "上腕二頭筋",
    secondaryMuscles: [],
    requiredEquipment: ["dumbbell"],
    requiresBenchAngle: false,
    loadType: "dumbbellPerHand",
    unilateral: false,
    defaultPieceCount: 2,
    formTips: ["肘の位置を固定する", "反動を使わない", "手首を曲げない"],
    commonMistakes: ["体を反らして反動をつける"],
    alternativeExerciseIds: [],
    materialStatus: "unconfirmed",
    repRangeByGoal: repRangeFor("isolation"),
    description: "両手にダンベルを持ち肘を曲げ伸ばしする。",
  },
  {
    id: "dumbbell-triceps-extension",
    name: "ダンベルトライセップエクステンション",
    primaryMuscle: "上腕三頭筋",
    secondaryMuscles: [],
    requiredEquipment: ["dumbbell"],
    requiresBenchAngle: false,
    loadType: "dumbbellPerHand",
    unilateral: false,
    defaultPieceCount: 1,
    formTips: ["ダンベル1個を両手で頭上に保持する", "肘の位置を動かさない", "肩がすくまないようにする"],
    commonMistakes: ["肘が開く", "可動域が浅い"],
    alternativeExerciseIds: [],
    materialStatus: "unconfirmed",
    repRangeByGoal: repRangeFor("isolation"),
    description: "ダンベル1個を両手で頭上に持ち、肘を曲げ伸ばしする。",
  },
  {
    id: "dumbbell-lateral-raise",
    name: "ダンベルサイドレイズ",
    primaryMuscle: "三角筋中部",
    secondaryMuscles: [],
    requiredEquipment: ["dumbbell"],
    requiresBenchAngle: false,
    loadType: "dumbbellPerHand",
    unilateral: false,
    defaultPieceCount: 2,
    formTips: ["肘を軽く曲げたまま真横に上げる", "肩の高さまでで止める", "反動を使わない"],
    commonMistakes: ["僧帽筋がすくむ", "反動で振り上げる"],
    alternativeExerciseIds: [],
    materialStatus: "unconfirmed",
    repRangeByGoal: repRangeFor("isolation"),
    description: "両手のダンベルを真横に肩の高さまで上げる。",
  },
  {
    id: "dumbbell-front-raise",
    name: "ダンベルフロントレイズ",
    primaryMuscle: "三角筋前部",
    secondaryMuscles: [],
    requiredEquipment: ["dumbbell"],
    requiresBenchAngle: false,
    loadType: "dumbbellPerHand",
    unilateral: false,
    defaultPieceCount: 2,
    formTips: ["体の前でダンベルを肩の高さまで上げる", "反動を使わない"],
    commonMistakes: ["体を反らして反動をつける"],
    alternativeExerciseIds: [],
    materialStatus: "unconfirmed",
    repRangeByGoal: repRangeFor("isolation"),
    description: "両手のダンベルを体の前で肩の高さまで上げる。",
  },
  {
    id: "dumbbell-bent-over-row",
    name: "ダンベルベントオーバーロウ",
    primaryMuscle: "広背筋",
    secondaryMuscles: ["僧帽筋", "三角筋後部"],
    requiredEquipment: ["dumbbell"],
    requiresBenchAngle: false,
    loadType: "dumbbellPerHand",
    unilateral: false,
    defaultPieceCount: 2,
    formTips: ["股関節から前傾する", "肘を後ろに引く", "背中を丸めない"],
    commonMistakes: ["腰が丸まる", "反動を使う"],
    alternativeExerciseIds: ["dumbbell-one-arm-row"],
    materialStatus: "unconfirmed",
    repRangeByGoal: repRangeFor("compound"),
    description: "前傾姿勢で両手のダンベルを同時に引き上げる。",
  },
  {
    id: "dumbbell-lunge",
    name: "ダンベルランジ",
    primaryMuscle: "大腿四頭筋",
    secondaryMuscles: ["臀筋"],
    requiredEquipment: ["dumbbell"],
    requiresBenchAngle: false,
    loadType: "dumbbellPerHand",
    unilateral: true,
    defaultPieceCount: 2,
    formTips: ["両手にダンベルを保持し体側で固定する", "前脚の膝がつま先より前に出過ぎない", "左右交互または片側ずつ行う"],
    commonMistakes: ["上体が前に倒れる", "膝が内側に入る"],
    alternativeExerciseIds: ["bodyweight-squat"],
    materialStatus: "unconfirmed",
    repRangeByGoal: repRangeFor("compound"),
    description: "両手にダンベルを持ち片脚ずつ踏み出す。踏み出す脚の左右を記録する。",
  },
  {
    id: "dumbbell-romanian-deadlift",
    name: "ダンベルルーマニアンデッドリフト",
    primaryMuscle: "ハムストリングス",
    secondaryMuscles: ["臀筋", "脊柱起立筋"],
    requiredEquipment: ["dumbbell"],
    requiresBenchAngle: false,
    loadType: "dumbbellPerHand",
    unilateral: false,
    defaultPieceCount: 2,
    formTips: ["膝を軽く曲げたまま股関節から折りたたむ", "ダンベルを体に沿わせる", "背中を丸めない"],
    commonMistakes: ["背中が丸まる", "膝が曲がりすぎる"],
    alternativeExerciseIds: [],
    materialStatus: "unconfirmed",
    repRangeByGoal: repRangeFor("compound"),
    description: "両手のダンベルを体に沿わせながら股関節を折りたたむ。",
  },
  {
    id: "dumbbell-hip-thrust",
    name: "ダンベルヒップスラスト",
    primaryMuscle: "臀筋",
    secondaryMuscles: ["ハムストリングス"],
    requiredEquipment: ["dumbbell", "bench"],
    requiresBenchAngle: false,
    loadType: "dumbbellPerHand",
    unilateral: false,
    defaultPieceCount: 1,
    formTips: ["肩甲骨をベンチに乗せる", "ダンベル1個を骨盤の上に両手で保持する", "腰を反らしすぎない"],
    commonMistakes: ["腰で反動をつける", "可動域が浅い"],
    alternativeExerciseIds: ["bodyweight-hip-lift"],
    materialStatus: "unconfirmed",
    repRangeByGoal: repRangeFor("compound"),
    description: "肩甲骨をベンチに乗せ、ダンベル1個を骨盤上で保持して腰を上げ下げする。ベンチの角度は不要（平置き）。",
  },
  {
    id: "dumbbell-floor-press",
    name: "ダンベルフロアプレス",
    primaryMuscle: "大胸筋",
    secondaryMuscles: ["上腕三頭筋"],
    requiredEquipment: ["dumbbell"],
    requiresBenchAngle: false,
    loadType: "dumbbellPerHand",
    unilateral: false,
    defaultPieceCount: 2,
    formTips: ["床に仰向けになり両手にダンベルを持つ", "上腕が床につくまで下ろす", "手首を立てたまま押し上げる"],
    commonMistakes: ["反動を使う"],
    alternativeExerciseIds: ["dumbbell-bench-press"],
    materialStatus: "unconfirmed",
    repRangeByGoal: repRangeFor("compound"),
    description: "ベンチを使わず床に仰向けで行うプレス種目。ベンチが使えない場合の代替。",
  },
  {
    id: "bodyweight-squat",
    name: "自重スクワット",
    primaryMuscle: "大腿四頭筋",
    secondaryMuscles: ["臀筋"],
    requiredEquipment: [],
    requiresBenchAngle: false,
    loadType: "bodyweight",
    unilateral: false,
    defaultPieceCount: 1,
    formTips: ["膝がつま先より内側に入らない", "股関節から折りたたむ", "かかとをつけたまま行う"],
    commonMistakes: ["かかとが浮く"],
    alternativeExerciseIds: ["goblet-squat"],
    materialStatus: "unconfirmed",
    repRangeByGoal: repRangeFor("bodyweight"),
    description: "器具なしで行うスクワット。ダンベルが最小重量でも難しい場合の代替種目。",
  },
  {
    id: "bodyweight-hip-lift",
    name: "自重ヒップリフト",
    primaryMuscle: "臀筋",
    secondaryMuscles: ["ハムストリングス"],
    requiredEquipment: [],
    requiresBenchAngle: false,
    loadType: "bodyweight",
    unilateral: false,
    defaultPieceCount: 1,
    formTips: ["肩甲骨を床につけたまま行う", "腰を反らしすぎない"],
    commonMistakes: ["反動をつける"],
    alternativeExerciseIds: ["dumbbell-hip-thrust"],
    materialStatus: "unconfirmed",
    repRangeByGoal: repRangeFor("bodyweight"),
    description: "床の上で行うヒップリフト。器具不要。",
  },
  {
    id: "plank",
    name: "プランク",
    primaryMuscle: "体幹",
    secondaryMuscles: [],
    requiredEquipment: [],
    requiresBenchAngle: false,
    loadType: "bodyweight",
    unilateral: false,
    defaultPieceCount: 1,
    formTips: ["体を一直線に保つ", "腰が落ちないようにする"],
    commonMistakes: ["腰が反る・落ちる"],
    alternativeExerciseIds: [],
    materialStatus: "unconfirmed",
    repRangeByGoal: repRangeFor("bodyweight"),
    description: "うつ伏せで肘とつま先で体を支える。回数欄は秒数として記録する。",
  },
  {
    id: "dumbbell-incline-bench-press",
    name: "ダンベルインクラインベンチプレス",
    primaryMuscle: "大胸筋上部",
    secondaryMuscles: ["三角筋前部", "上腕三頭筋"],
    requiredEquipment: ["dumbbell", "bench"],
    requiresBenchAngle: true,
    loadType: "dumbbellPerHand",
    unilateral: false,
    defaultPieceCount: 2,
    formTips: ["ベンチを傾斜させ仰向けになる", "ダンベルは胸上部の横まで下ろす"],
    commonMistakes: ["肩がすくむ"],
    alternativeExerciseIds: ["dumbbell-bench-press"],
    materialStatus: "unconfirmed",
    repRangeByGoal: repRangeFor("compound"),
    description:
      "ベンチを傾斜させて行う種目。STEADY ST123の角度調整仕様が未確認のため、確認できるまで提案候補に出さない。",
  },
];
